name: CI
on: pull_request

jobs:
  eslint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install ESLint formatter
        run: npm install @microsoft/eslint-formatter-sarif@2.1.7

      - name: Run ESLint
        run: npm run lint --
          --max-warnings=0
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif

      - name: Upload analysis results to GitHub
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run typecheck
        run: npm run typecheck

  deploy:
    name: Deploy
    if: github.base_ref == 'master'
    needs: [eslint, typecheck]
    uses: ./.github/workflows/cd.yml
